 - name: "conditions exampples"
   hosts: local
   connection: local
   vars:
    COURSE: "DEVOPSECOPS"
    DURATION: 100
    SYLLABUS: ["SHELLSCRIPT","ANSIBLE","DOCKER"]
    debug_mode: false
   tasks:
    - name: "checking the course name"
      ansible.builtin.debug:
       msg: "course name is matched"
      when: COURSE == "DEVOPSECOPS"
    - name: "checking the duration"
      ansible.builtin.debug:
       msg: "course duration is as expected"
      when: DURATION == 100 and COURSE == "DEVOPSECOPS"
    - name: "checking syllabus"
      ansible.builtin.debug:
        msg: "syllabus is gud"
      when: "'SHELLSCRIPT' in SYLLABUS"
    - name: "checking debug mode"
      ansible.builtin.debug:
        msg: "run if debug mode set as true"
      when: debug_mode | bool
    - name: "checking the duration"
      ansible.builtin.debug:
       msg: "course duration is as expected"
      when: DURATION == 100 or COURSE == "fullstack"
    - name: "checking the duration"
      ansible.builtin.debug:
       msg: "course duration is as expected"
      when: DURATION == 100 and COURSE == "fullstack"
    
